### ISSUE TITLE
Show button not displayed for folders/labels

### ISSUE THREAD

**Issue by jackiehluo** [oeaeee/n1-stripe#2]
If you don't already have your folders/labels for inboxes shown, there's no way to see them because the show (and hide) button is missing! Normally visible on hover:

<img width="156" alt="screen shot 2016-04-05 at 10 23 28 am" src="https://cloud.githubusercontent.com/assets/8452682/14291436/75156902-fb18-11e5-9259-b453adf5bc3e.png">

**Comment by oeaeee** [comment]
Aha. I wasn't crazy about how the show/hide interaction worked in the horizontal layout. The temporary solve was: show all folders always (and hide the show/hide button). Forgot folders might be collapsed to begin with.

Just updated with a modified folder header layout. Functionality back in!

**Comment by jackiehluo** [comment]
Ooh, cool! Thanks!
