### ISSUE TITLE
Alignment issue (minor)

### ISSUE THREAD

**Issue by zlatkobijelic** [oeaeee/n1-stripe#4]
Just noticed this and thought I would point it out: http://d.pr/i/1iuq0 - the '**read / unread** indicator is a bit off.

**Comment by oeaeee** [comment]
I added several alignment fixes last week. I don't personally get an Unread marker in the header for my emails so I couldn't test the particular case you were seeing, but the additions should keep more things vertically centered generally. Hope it catches what you were seeing!

**Comment by zlatkobijelic** [comment]
This looks good now - just waiting for this fix: https://github.com/oeaeee/n1-stripe/issues/3 - still seeing the issue with accounts not showing up at the **bottom**
