### ISSUE TITLE
Small UI Bug when using the theme on OS X 

### ISSUE THREAD

**Issue by technocidal** [oeaeee/n1-stripe#6]
Hey,

first I really love your approach but I just noticed this UI collision. It makes it nearly impossible to click the buttons and overall looks wrong. Maybe you can have a look into this. It happens in windowed and in fullscreen mode.
I`m using 
<b>Nylas Version 0.4.45-7637265 (0.4.45-7637265)</b> on a 2013 MacBook Pro Retina with <b>El Capitan 10.11.6 Beta (15G12a)</b>.

Best regards
<img width="806" alt="bildschirmfoto 2016-06-15 um 16 23 38" src="https://cloud.githubusercontent.com/assets/14994778/16083705/4b278982-3316-11e6-9c9e-d3648f446a70.png">

**Comment by oeaeee** [comment]
I think this probably came about with yesterday's launch. I'll try to get to it soon. Thanks.

**Comment by oeaeee** [comment]
Added a fix for this a few days ago.
